spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 20

  jpa:
    show-sql: false

jwt:
  secret: ${JWT_SECRET}

server:
  error:
    include-message: never
    include-binding-errors: never

logging:
  level:
    root: WARN
    br.com.bitabit.ecclesiacontrol: INFO